---
title: "Contents"
description: "Workshop learning materials. Slides: {{< fa file-powerpoint >}} / {{< fa file-pdf >}}, Labs: {{< fa file-lines >}}, Videos: {{< fa brands youtube >}}"
date: ""
toc: false
number-sections: false
sidebar: false
format: html
---

::: {.callout-note}
Note that the slides and videos may not be in sync because the slides were updated while the videos are from previous workshops.
:::

|Topic|Presenter|Links|
|---|---|---|
|Introduction to Linux|Martin Dahlö|[[{{< fa brands youtube >}} Video](https://youtu.be/qYp8shSMJ-0)]{.badge} [[{{< fa file-pdf >}} Slides](topics/linux/slide_linux_intro.pdf)]{.badge} [[{{< fa file-lines >}} Lab](topics/linux/lab_linux_intro.html)]{.badge}|
|Linux file permissions|Martin Dahlö|[[{{< fa file-lines >}} Lab](topics/linux/lab_linux_permissions.html)]{.badge}|
|Introduction to HPC|Martin Dahlö|[[{{< fa brands youtube >}} Video](https://youtu.be/cxEtfKN91q4)]{.badge} [[{{< fa file-pdf >}} Slides](topics/hpc/intro/slide_hpc_intro.pdf)]{.badge} [[{{< fa file-lines >}} Lab](topics/hpc/intro/lab_intro.html)]{.badge}|
|HPC pipelines|Martin Dahlö|[[{{< fa file-lines >}} Lab](topics/hpc/pipeline/lab_pipeline.html)]{.badge}|
|File types in Linux|Martin Dahlö|[[{{< fa brands youtube >}} Video](https://youtu.be/7MR1qUZQ94w)]{.badge} [[{{< fa file-pdf >}} Slides](topics/linux/slide_linux_filetypes.pdf)]{.badge} [[{{< fa file-lines >}} Lab](topics/linux/lab_linux_filetypes.html)]{.badge}|
|Better terminal experience|Martin Dahlö|[[{{< fa brands youtube >}} Video](https://youtu.be/RGbONVWOaDo)]{.badge} [[{{< fa file-pdf >}} Slides](topics/linux/slide_qol_termexp.pdf)]{.badge}|
|QC of FastQ reads|Marcel Martin|[[{{< fa file-pdf >}} Slides](topics/other/slide_qc.pdf)]{.badge} [[{{< fa file-lines >}} Lab](topics/other/lab_qc.html)]{.badge}|
|Advanced Linux|Martin Dahlö|[[{{< fa brands youtube >}} Video](https://youtu.be/n3IpUHIodM8)]{.badge} [[{{< fa file-pdf >}} Slides](topics/linux/slide_linux_advanced.pdf)]{.badge} [[{{< fa file-lines >}} Lab](topics/linux/lab_linux_advanced.html)]{.badge}|
|NGS technologies and challenges|NGI|[[{{< fa brands youtube >}} Video](https://youtu.be/5sUzkrucL1E)]{.badge} [[{{< fa file-pdf >}} Slides](https://drive.google.com/file/d/14kfPifL52eMTZs2jsrykPehFBVpAxWr/view?usp=sharing)]{.badge}|
|NGS long reads and pipelines|NGI|[[{{< fa brands youtube >}} Video](https://youtu.be/6RBhfMvDkSI)]{.badge} [[{{< fa file-pdf >}} Slides](https://drive.google.com/file/d/1U_oVEuTTKwk7zxVP_CGR5zgHP6Jd_1Oi/view?usp=sharing)]{.badge}|
|Variant-calling workflow|Diana Ekman|[[{{< fa brands youtube >}} Video](https://youtu.be/NxRECdxKP40)]{.badge} [[{{< fa file-powerpoint >}} Slides](topics/vc/slide_vc.pptx)]{.badge} [[{{< fa file-lines >}} Lab](topics/vc/lab_vc.html)]{.badge}|
|RNA-Seq workflow|Roy Francis / Dag Ahrén|[[{{< fa brands youtube >}} Video](https://youtu.be/gC_nslHgSa8)]{.badge} [[{{< fa brands html5 >}} Slides](topics/rnaseq/slide_rnaseq.html)]{.badge} [[{{< fa file-lines >}} Lab](topics/rnaseq/lab_rnaseq.html)]{.badge}|
|Data management|NBIS DM|[[{{< fa brands youtube >}} Video](https://youtu.be/PfcrDlhY1zE)]{.badge} [[{{< fa file-powerpoint >}} Slides](topics/other/slide_data_management.pdf)]{.badge}|

### Useful resources

- Connecting to HPC PDC [{{< fa file-lines >}}](topics/other/lab_connect_pdc.html)
- Connecting to HPC UPPMAX [{{< fa file-lines >}}](topics/other/lab_connect_uppmax.html)
- Uploading & downloading files from HPC [{{< fa file-lines >}}](topics/other/lab_download_files.html)
- Using X11 on Windows with VcXsrv [{{< fa file-lines >}}](topics/other/lab_vcxsrv.html)
- Simon's RNASeq analysis [{{< fa file-lines >}}](topics/rnaseq/simon-report/validating_knockout.html)
- Linux cheatsheet [{{< fa file-pdf >}}](topics/linux/assets/linux_cheat_sheet.pdf)
- Bash cheat sheet 1 [{{< fa file-pdf >}}](topics/linux/assets/bash_cheat_sheet_1.pdf)
- Bash cheat sheet 2 [{{< fa file-pdf >}}](topics/linux/assets/bash_cheat_sheet_2.pdf)
- Bash cheat sheet 3 [{{< fa file-pdf >}}](topics/linux/assets/bash_cheat_sheet_3.pdf)
- Uppmax cheatsheet [{{< fa file-image >}}](topics/linux/assets/uppmax_cheat_sheet.png)
- Mac keyboard [{{< fa file-lines >}}](topics/other/lab_mac_keyboard.html)

