---
title: "Content"
output:
  bookdown::html_document2:
    toc: false
    number_sections: false
---

```{r,child="assets/header-lab.Rmd"}
```

This page contains links to different lectures (slides) and practical exercises (labs) that are part of this workshop. The links below are similar to that under [Schedule](home_schedule.html) but organised here by topic.

**Introduction to Linux**

* [Intro to Linux (Slides)](slide_linux_intro.pdf)
* [Intro to Linux (Lab)](lab_linux_intro.html)

**File types in Linux**

* [Filetypes (Slides)](slide_linux_filetypes.pdf)
* [Filetypes (Lab)](lab_linux_filetypes.html)  

**Uppmax**

* [Intro to Uppmax (Slides)](slide_uppmax_intro.pdf)
* [Introduction to UPPMAX (Lab)](lab_uppmax_intro.html)  
* [UPPMAX Pipelines (Lab)](lab_uppmax_pipeline.html)

**Advanced Linux**

* [Better terminal experience (Slides)](slide_qol_termexp.pdf)
* [Advanced Linux (Slides)](slide_linux_advanced.pdf)
* [Advanced linux (Lab)](lab_linux_advanced.html)

**Variant-calling workflow**

* [Variant-calling (Slides)](slide_vc.pdf)
* [Variant-calling workflow (Lab)](lab_vc.html)
* [Variant-calling Lab discussion](slide_vc_discussion.pptx)

**RNA-Seq workflow**

* [RNA-Seq analyses (Slides)](slide_rnaseq.html)
* [RNA-Seq workflow (Lab)](lab_rnaseq.html)

**Other**

* [NGS Overview (Slides)](slide_Sequencing_technologies_2020b.pptx)


**Useful resources**

* [Linux cheatsheet](data/linux/linux_cheat_sheet.pdf)
* [Bash cheat sheet 1](data/linux/bash_cheat_sheet_1.pdf)
* [Bash cheat sheet 2](data/linux/bash_cheat_sheet_2.pdf)
* [Bash cheat sheet 3](data/linux/bash_cheat_sheet_3.pdf)
* [Uppmax cheatsheet](data/linux/uppmax_cheat_sheet.png)
* [Mac keyboard](lab_mac_keyboard.html)

***
