---
title: "Contents"
output:
  bookdown::html_document2:
    toc: false
    number_sections: false
---

```{r,child="assets/header-lab.Rmd"}
```

This page contains links to different lectures (slides) and practical exercises (labs) that are part of this workshop. The links below are similar to that under [Schedule](home_schedule.html) but organised here by topic. The schedule is intended for those following a live workshop (in-person or online).

**Introduction to Linux**

* [Introduction to Linux (Slides)](slide_linux_intro.pdf)
* [Introduction to Linux (Lab)](lab_linux_intro.html)

**File types in Linux**

* [File types in Bioinformatics (Slides)](slide_linux_filetypes.pdf)
* [File types in Bioinformatics (Lab)](lab_linux_filetypes.html)  
* [Linux file permissions (Lab)](lab_linux_permissions.html)

**Uppmax**

* [Introduction to UPPMAX (Slides)](slide_uppmax_intro.pdf)
* [Introduction to UPPMAX (Lab)](lab_uppmax_intro.html)  
* [UPPMAX Pipelines (Lab)](lab_uppmax_pipeline.html)

**Advanced Linux**

* [Better terminal experience (Slides)](slide_qol_termexp.pdf)
* [Advanced Linux (Slides)](slide_linux_advanced.pdf)
* [Advanced Linux (Lab)](lab_linux_advanced.html)

**Variant-calling workflow**

* [Variant-calling (Slides)](slide_vc.pptx)
* [Variant-calling workflow (Lab)](lab_vc.html)
<!--* [Variant-calling Lab answers](lab_vc_answers.pdf)-->

**RNA-Seq workflow**

* [RNA-Seq analyses (Slides)](slide_rnaseq.html)
* [RNA-Seq workflow (Lab)](lab_rnaseq.html)

**Other**

* [NGS technologies and challenges (Slides)](slide_sequencing.pdf)
* [NGS Pipelines (Slides)](slide_ngs_pipelines.pdf)


<!--* [Data management (Slides)](slide_data_management.pdf)-->

**Useful resources**

* [Connecting to Uppmax](lab_connect.html)
* [Linux cheatsheet](data/linux/linux_cheat_sheet.pdf)
* [Bash cheat sheet 1](data/linux/bash_cheat_sheet_1.pdf)
* [Bash cheat sheet 2](data/linux/bash_cheat_sheet_2.pdf)
* [Bash cheat sheet 3](data/linux/bash_cheat_sheet_3.pdf)
* [Uppmax cheatsheet](data/linux/uppmax_cheat_sheet.png)
* [Mac keyboard](lab_mac_keyboard.html)

***
