---
title: "HPC IO"
subtitle: "Downloading and uploading files from HPC cluster"
date: ""
format: html
---

## Local workspace

Start by creating a folder on your laptop where the files that you will download should end up. You need to have write permission in this folder. This folder will be referred to as your *local workspace* throughout these instructions.

Open a terminal window on your laptop and move into your local workspace.

## Download a file from HPC

Lets assume that you have a file "results.txt" in the following folder on HPC:

```
{{< meta path_workspace >}}/somefolder/
```

::: {.callout-note}
`username` and `somefolder` should be replaced with your real username and a real folder name. Run this in a LOCAL terminal.
:::

To download the file to your local workspace type:

```sh
scp username@{{< meta url_cluster >}}:{{< meta path_workspace >}}/somefolder/results.txt .
```

Note that the last `.` means that the file will be downloaded to the current directory on your local machine.

If you want to download an entire folder from HPC to your local workspace, you can use the `-r` option with `scp`:

```sh
scp -r username@{{< meta url_cluster >}}:{{< meta path_workspace >}}/somefolder .
```

If you want to use wildcards to download multiple files at once, you can use patterns like `*.txt` to match all text files:

```sh
scp 'username@{{< meta url_cluster >}}:{{< meta path_workspace >}}/somefolder/*.txt' .
```

Note the use of single quotes around the remote path when using wildcards. This prevents the local shell from expanding the wildcard before it is sent to the remote server.

## Upload a file to HPC

Now lets imagine that you have developed a script on your laptop and want to upload it to HPC. The script is stored on your local machine and is called "script.sh". Type this in your local workspace to upload the file to HPC:

::: {.callout-note}
`username` and `somefolder` should be replaced with your real username and a real folder name. Run this in a LOCAL terminal.
:::

```sh
scp script.sh username@{{< meta url_cluster >}}:{{< meta path_workspace >}}/somefolder/
```
