---
title:  "Status & Troubleshooting"
subtitle: "Utility commands/scripts, troubleshooting, tips and suggestions."
date: ""
sidebar: false
format: html
---

```{r}
#| echo: false
library(yaml)
library(here)
id_project <- yaml::read_yaml(here("_quarto.yml"))$id_project
```

## Status

Useful commands for monitoring status and user activity on HPC.

### List jobs

List all jobs running an a project

```sh
squeue -A {{< meta id_project >}} | sort -k 4
```

Sample output

```
  23186770      core _interac analopez  R    2:15:00      1 r55
  23175660      core   (null)   anitav  R    6:52:28      1 r480
  23188713      core   (null)    annha  R    1:42:59      1 r480
  23185442      core   (null)    annha  R    2:47:11      1 r480
  23185433      core   (null) inene424  R    2:47:42      1 r479
  23185391      core   (null) inene424  R    2:50:04      1 r479
  23185540      core   (null)  shengyz  R    2:46:20      1 r480
     JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
  23185119      core   (null)    wingf  R    2:53:40      1 r479
```

### Jobs per user

Sorted list of jobs per user

```sh
squeue -A {{< meta id_project >}} | tr -s ' ' | cut -d' ' -f5 | sort | uniq -c | sort -k1
```

Sample output

```
      1 tami
      1 tommal
      1 USER
      1 valeriia
      1 vioww
      1 vishnupk
      1 ylvafr
      2 mehran96
      2 miika
      3 mariasve

```

### Core usage

Total number of cores used on a project

```sh
squeue -A {{< meta id_project >}} -o %C | awk '{total += $0} END{print total}'
```

### Space usage

Amount of storage space used per project

```sh
projinfo
```

Sample output

```
Information for compute project: edu24.uppmax (PI: mdahlo)
UPPMAX intro course
Active from 2024-09-29 00:00:00 to 2025-02-03 00:00:00
Members: asmae,ccollins,dianaek,emmers,eswku,heddaja,larsger,laurea,leonco,malina,mariaio,marziar,mdahlo,muyi,peihung,royfranc,rubencw,shaja23,svelo,szczot,theoseri,tudoran,vibe1827,xuji
dardel: 2000 corehours/month, used 39.51% (790 corehours) during the past 30 days
Usage by user royfranc: 36.85% (736 corehours)
```

### List project members

```sh
projinfo
```

Sample output

```
Information for compute project: edu24.uppmax (PI: mdahlo)
UPPMAX intro course
Active from 2024-09-29 00:00:00 to 2025-02-03 00:00:00
Members: asmae,ccollins,dianaek,emmers,eswku,heddaja,larsger,laurea,leonco,malina,mariaio,marziar,mdahlo,muyi,peihung,royfranc,rubencw,shaja23,svelo,szczot,theoseri,tudoran,vibe1827,xuji
dardel: 2000 corehours/month, used 39.51% (790 corehours) during the past 30 days
Usage by user royfranc: 36.85% (736 corehours)
```

### User activity

List last activity in a directory for all users

```sh
bash /sw/courses/utils/list_modification_times.sh /proj/{{< meta id_project >}}/nobackup/
```

Sample output

```
hkyle           2021-11-22 13:59:59     (/proj/snic2021-22-644/nobackup/hkyle/uppmax_tutorial/job_template)
malinh          2021-11-22 14:12:10     (/proj/snic2021-22-644/nobackup/malinh/slurm-23182638.out)
aliraz          2021-11-22 14:23:16     (/proj/snic2021-22-644/nobackup/aliraz/slurm-23184022.out)
kristaps        2021-11-22 14:25:08     (/proj/snic2021-22-644/nobackup/kristaps/uppmax_tutorial/jobData.sam)
anapin          2021-11-22 14:56:14     (/proj/snic2021-22-644/nobackup/anapin/uppmax_tutorial/uppmax_tutorial/jobData.sam)
analopez        2021-11-22 14:56:16     (/proj/snic2021-22-644/nobackup/analopez/uppmax_tutorial/jobData.sam)
private         Not available     ()
```

### List reservations for a project

```sh
scontrol show res | grep {{< meta id_project >}}
```

Sample output

```
ReservationName=snic2021-22-644_wed StartTime=2021-11-24T12:00:00 EndTime=2021-11-24T18:00:00 Duration=06:00:00
   Users=(null) Accounts=snic2021-22-644 Licenses=(null) State=INACTIVE BurstBuffer=(null) Watts=n/a
ReservationName=snic2021-22-644_thu StartTime=2021-11-25T08:30:00 EndTime=2021-11-25T17:30:00 Duration=09:00:00
   Users=(null) Accounts=snic2021-22-644 Licenses=(null) State=INACTIVE BurstBuffer=(null) Watts=n/a
ReservationName=snic2021-22-644_fri StartTime=2021-11-26T08:30:00 EndTime=2021-11-26T13:30:00 Duration=05:00:00
   Users=(null) Accounts=snic2021-22-644 Licenses=(null) State=INACTIVE BurstBuffer=(null) Watts=n/a
```

### User identity

Fetch user information from username

```sh
finger username
```

## Troubleshooting

### X-forwarding

#### Setup

**Mac users**

- Install Xquartz and restart computer
- Open the Xquartz terminal and connect to Uppmax 
- In my recent macos (10.xxx) , x-forwarding only works if I explicitly run the Xquartz terminal

`ssh -XY username@{{< meta url_cluster >}}`  
`ssh -XY username@{{< meta url_cluster_backup >}}`

Also use this when logging in to the compute node!

`ssh -XY username@node`

**Windows users**

In MobaXTerm, go to settings and make sure that X-forwarding is checked.

#### Testing X-forwarding on Rackham

Type `xeyes` in the terminal.

### Open .html documents on Rackham

First ensure X-forwarding works, then run `firefox --no-remote filename.html`

### SCP fails with *

Sometimes students have problems to download files with SCP when there is a `*` in the end of the line. For example; `scp user@{{< meta url_cluster >}}:~/ngsintro/HG00097.bam* .`. It needs to be changed to `scp user@{{< meta url_cluster >}}:~/ngsintro/HG00097.bam\* .`.

### Thinlinc

#### Login

When logging in through an installed client, **username/password** seems to work. When logging in through the browser, **username/password+2FA** may be required.

#### Minimize the ThinLinc window

On a  Mac, press <kbd>Fn + F8</kbd>, then select: Minimize window. 

#### Gedit opening issues

When opening it from the terminal (`gedit &`), it was not able to connect to a display to show the graphics. The `DISPLAY` variable was empty. This was when using ThinLinc, so it should have worked. The issue was solved by opening gedit from the menu. Gedit could be labelled Text Editor. 

### Set persistent home directory in MobaXTerm

This is to specify where the **home directory** in MobaXTerm is located in the computer’s file system. In **Settings > Configuration**, set the persistent home directory to a suitable folder. Restart MobaXTerm. 

### Typing `$` on a Swedish keyboard

Press <kbd>AltGr + 4</kbd>.

### Black background for XQuartz windows on M1 Mac

As documented [here](https://github.com/XQuartz/XQuartz/issues/31), run:

```sh
defaults write org.xquartz.X11 enable_render_extension 0
```

### Thinlinc client installs in Swedish

There seems to be no option to change language in the app. So one will have to reinstall with some changes. In region settings, if English is set as primary and Swedish as secondary, it still installs in Swedish. The solution is to remove Swedish from the list completely and then reinstall.

***
