name: apptainer

on:
  workflow_dispatch:
    inputs:
      quarto_version:
        description: Quarto version to install
        required: true
        default: "1.10.18"
        type: string

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}-apptainer
  VERSION: "2.5.1"
  QUARTO_VERSION: ${{ inputs.quarto_version }}

jobs:
  apptainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Build Apptainer image
        working-directory: container
        run: |
          sudo apptainer build \
            --build-arg QUARTO_VERSION="${QUARTO_VERSION}" \
            workshop-ngsintro.sif apptainer.def

      - name: Test Apptainer image
        working-directory: container
        run: |
          apptainer exec workshop-ngsintro.sif quarto --version
          apptainer exec workshop-ngsintro.sif pixi --version
          apptainer exec workshop-ngsintro.sif samtools --version

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | apptainer registry login \
            --username "${{ github.actor }}" \
            --password-stdin oras://ghcr.io

      - name: Push Apptainer image
        working-directory: container
        run: |
          apptainer push workshop-ngsintro.sif \
            "oras://${IMAGE_NAME}:${VERSION}"
          apptainer push workshop-ngsintro.sif \
            "oras://${IMAGE_NAME}:latest"
