name: build
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  rmd-render-job:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-18.04, r: '4.0.0'}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
        with:
          r-version: ${{ matrix.config.r }}
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev libopenblas-base
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          rm -rf google-chrome-stable_current_amd64.deb
      - name: Define variables
        run: |
          echo "path_repo=$(pwd)" >> $GITHUB_ENV
          echo "path_export=$(grep -E '^output_dir' _site.yml | sed 's/^output_dir://' | xargs)" >> $GITHUB_ENV
          echo "path_export_canvas=$(grep -E '^output_dir' _site.yml | sed 's/^output_dir://' | xargs)-canvas" >> $GITHUB_ENV
          echo "repo=$(echo $GITHUB_REPOSITORY | sed 's/.*\///')" >> $GITHUB_ENV
      - name: Check R installation and variables
        run: |
          Rscript -e "print('R installation works!')"
          echo "Github actor: ${GITHUB_ACTOR}"
          echo "Github repository: ${GITHUB_REPOSITORY}"
          echo "Github repo: ${repo}"
          echo "Path repo: ${path_repo}"
          echo "Path export: ${path_export}"
          echo "Path export canvas: ${path_export_canvas}"
          echo "---------------------------------------------------------------------------------------------"
          echo "Folder contents at $(pwd):"
          ls -lh
          echo "---------------------------------------------------------------------------------------------"
          printenv
          sed --version
      - name: Print R packages
        run: |
          # parse r packages from Rmd amd md files
          # grep -Eroh "(^library\([A-Za-z0-9]+\))|(^require\([A-Za-z0-9]+\))" *md | sed 's/library\|(\|)//g' | sort | uniq > r-packages.txt
          # parse r packages from _site.yml
          awk '/^[^ ]/{ f=/^packages:/; next } f{ if (sub(/:$/,"")) pkg=$2; else print pkg, $2 }' _site.yml | uniq | sort > r-packages.txt
          cat r-packages.txt
      - name: Cache R packages
        id: cache-rp
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ matrix.config.r }}-${{ hashFiles('r-packages.txt') }}
      - name: Install R dependencies
        if: steps.cache-rp.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("yaml","pagedown"))'
          Rscript -e 'if(!is.null(yaml::read_yaml("_site.yml")$packages$packages_cran_repo)) install.packages(yaml::read_yaml("_site.yml")$packages$packages_cran_repo)'
          Rscript -e 'if(!is.null(yaml::read_yaml("_site.yml")$packages$packages_cran_student)) install.packages(yaml::read_yaml("_site.yml")$packages$packages_cran_student)'
          Rscript -e 'if(!is.null(yaml::read_yaml("_site.yml")$packages$packages_bioc_repo)) BiocManager::install(as.character(yaml::read_yaml("_site.yml")$packages$packages_bioc_repo))'
          Rscript -e 'if(!is.null(yaml::read_yaml("_site.yml")$packages$packages_bioc_student)) BiocManager::install(as.character(yaml::read_yaml("_site.yml")$packages$packages_bioc_student))'
          Rscript -e 'if(!is.null(yaml::read_yaml("_site.yml")$packages$packages_github_repo)) remotes::install_github(yaml::read_yaml("_site.yml")$packages$packages_github_repo)'
          Rscript -e 'if(!is.null(yaml::read_yaml("_site.yml")$packages$packages_github_student)) remotes::install_github(yaml::read_yaml("_site.yml")$packages$packages_github_student)'
          Rscript -e 'installed.packages()'
          echo "R directory size:"
          du -sh ${{ env.R_LIBS_USER }}
      - name: Render site, pull repo, copy folder, create index, push repo
        run: |
          # Add git info
          git config --global user.email "do_not_email@example.com"
          git config --global user.name "gh_action"

          # Render website
          Rscript -e "rmarkdown::render_site()"

          # Render canvas version of website by changing _site.yml
          # suffixes output directory with -canvas
          # adds current output directory to be ignored
          # renames navbar block to remove menu
          # removes footer
          #sed 's/\(output_dir:\)\s*\([0-9]*\)/\1 \2-canvas/' _site.yml | \
          #sed "/^exclude/s/\]$/,\"${path_export}\"]/" | \
          #sed 's/navbar:/unused:/' | \
          #sed 's/include://' | \
          #sed 's/after_body: assets\/footer-lab.html//' > _site.yml

          Rscript -e 'y <- yaml::read_yaml("_site.yml"); y$exclude <- append(y$exclude,y$output_dir); y$output_dir <- paste0(y$output_dir,"-canvas"); y$navbar <- NULL; y$output$`bookdown::html_document2`$include <- NULL; yaml::write_yaml(y,"_site.yml");'

          ls -lh
          cat _site.yml
          Rscript -e "rmarkdown::render_site()"

          # Generate PDFs
          cd ${path_export}
          Rscript -e "l <- list.files('.',pattern='slide.+html');if(length(l)!=0) {for(i in 1:length(l)) pagedown::chrome_print(l[i])};"
          cd ..
          cd ${path_export_canvas}
          Rscript -e "l <- list.files('.',pattern='slide.+html');if(length(l)!=0) {for(i in 1:length(l)) pagedown::chrome_print(l[i])};"
          cd ..

          # List folder contents
          echo "Folder contents at $(pwd):"
          ls -lh
          echo "Folder contents at ${path_repo}/${path_export}:"
          ls -lh ${path_repo}/${path_export}
          echo "Folder contents at ${path_repo}/${path_export_canvas}:"
          ls -lh ${path_repo}/${path_export_canvas}

          # Clone gh-pages branch and remove old directories with same name
          git clone --single-branch --branch gh-pages "https://${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" tmprepo
          cd tmprepo
          if [ -d $path_export ]; then
            echo "Directory ${path_export} already exists. Removing the directory."
            git rm -r $path_export
            git commit -m "Old directory ${path_export} deleted."
          fi
          if [ -d $path_export_canvas ]; then
            echo "Directory ${path_export_canvas} already exists. Removing the directory."
            git rm -r $path_export_canvas
            git commit -m "Old directory ${path_export_canvas} deleted."
          fi

          cd ${path_repo}
          cp -r $path_export tmprepo/
          cp -r $path_export_canvas tmprepo/
          cd tmprepo
          echo "Folder contents at $(pwd):"
          ls -lh

          # Create index file
          url_git=$(git config --get remote.origin.url)
          echo "Repo: $url_git"
          str_user=$(echo $url_git | sed -E 's/http.+github.com\/|\.git//g' | sed 's/\/.*//')
          echo "User: $str_user"

          printf "All current and previous workshop materials are listed below.\n\n" > index.md
          printf "<div style='display:block;'><p style='line-height:2;'>\n" >> index.md
          months=(Zero Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec)
          dirs=$(ls -d [0-9]*[0-9]/ | sed 's/\///' | tac)
          for i in $dirs
          do
           printf "<span style='display:block;'><a href='https://${str_user}.github.io/${repo}/${i}/'>20${i:0:2} ${months[${i:(-2)}]}</a></span>" >> index.md
          done
          printf "</p></div>" >> index.md

          echo "Folder contents at $(pwd):"
          ls -lh

          # Push changes back
          git add .
          git commit -m "Updated contents at $(date +%Y%m%d-%H%M%S)"
          git push origin
